/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.desafio.ponto.model;

import aQute.bnd.annotation.ProviderType;

import com.desafio.ponto.service.persistence.PontoMarcacoesPK;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the PontoMarcacoes service. Represents a row in the &quot;ponto_marcacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.desafio.ponto.model.impl.PontoMarcacoesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.desafio.ponto.model.impl.PontoMarcacoesImpl}.
 * </p>
 *
 * @author Peterson Morais
 * @see PontoMarcacoes
 * @see com.desafio.ponto.model.impl.PontoMarcacoesImpl
 * @see com.desafio.ponto.model.impl.PontoMarcacoesModelImpl
 * @generated
 */
@ProviderType
public interface PontoMarcacoesModel extends BaseModel<PontoMarcacoes> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ponto marcacoes model instance should use the {@link PontoMarcacoes} interface instead.
	 */

	/**
	 * Returns the primary key of this ponto marcacoes.
	 *
	 * @return the primary key of this ponto marcacoes
	 */
	public PontoMarcacoesPK getPrimaryKey();

	/**
	 * Sets the primary key of this ponto marcacoes.
	 *
	 * @param primaryKey the primary key of this ponto marcacoes
	 */
	public void setPrimaryKey(PontoMarcacoesPK primaryKey);

	/**
	 * Returns the pis of this ponto marcacoes.
	 *
	 * @return the pis of this ponto marcacoes
	 */
	public long getPis();

	/**
	 * Sets the pis of this ponto marcacoes.
	 *
	 * @param Pis the pis of this ponto marcacoes
	 */
	public void setPis(long Pis);

	/**
	 * Returns the data hora of this ponto marcacoes.
	 *
	 * @return the data hora of this ponto marcacoes
	 */
	public long getDataHora();

	/**
	 * Sets the data hora of this ponto marcacoes.
	 *
	 * @param DataHora the data hora of this ponto marcacoes
	 */
	public void setDataHora(long DataHora);

	/**
	 * Returns the marcacao_valida of this ponto marcacoes.
	 *
	 * @return the marcacao_valida of this ponto marcacoes
	 */
	public boolean getMarcacao_valida();

	/**
	 * Returns <code>true</code> if this ponto marcacoes is marcacao_valida.
	 *
	 * @return <code>true</code> if this ponto marcacoes is marcacao_valida; <code>false</code> otherwise
	 */
	public boolean isMarcacao_valida();

	/**
	 * Sets whether this ponto marcacoes is marcacao_valida.
	 *
	 * @param Marcacao_valida the marcacao_valida of this ponto marcacoes
	 */
	public void setMarcacao_valida(boolean Marcacao_valida);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PontoMarcacoes pontoMarcacoes);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PontoMarcacoes> toCacheModel();

	@Override
	public PontoMarcacoes toEscapedModel();

	@Override
	public PontoMarcacoes toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}