/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.desafio.ponto.model;

import aQute.bnd.annotation.ProviderType;

import com.desafio.ponto.service.persistence.PontoDiaPK;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the PontoDia service. Represents a row in the &quot;ponto_dia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.desafio.ponto.model.impl.PontoDiaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.desafio.ponto.model.impl.PontoDiaImpl}.
 * </p>
 *
 * @author Peterson Morais
 * @see PontoDia
 * @see com.desafio.ponto.model.impl.PontoDiaImpl
 * @see com.desafio.ponto.model.impl.PontoDiaModelImpl
 * @generated
 */
@ProviderType
public interface PontoDiaModel extends BaseModel<PontoDia> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ponto dia model instance should use the {@link PontoDia} interface instead.
	 */

	/**
	 * Returns the primary key of this ponto dia.
	 *
	 * @return the primary key of this ponto dia
	 */
	public PontoDiaPK getPrimaryKey();

	/**
	 * Sets the primary key of this ponto dia.
	 *
	 * @param primaryKey the primary key of this ponto dia
	 */
	public void setPrimaryKey(PontoDiaPK primaryKey);

	/**
	 * Returns the pis of this ponto dia.
	 *
	 * @return the pis of this ponto dia
	 */
	public long getPis();

	/**
	 * Sets the pis of this ponto dia.
	 *
	 * @param Pis the pis of this ponto dia
	 */
	public void setPis(long Pis);

	/**
	 * Returns the data of this ponto dia.
	 *
	 * @return the data of this ponto dia
	 */
	public long getData();

	/**
	 * Sets the data of this ponto dia.
	 *
	 * @param Data the data of this ponto dia
	 */
	public void setData(long Data);

	/**
	 * Returns the competencia of this ponto dia.
	 *
	 * @return the competencia of this ponto dia
	 */
	@AutoEscape
	public String getCompetencia();

	/**
	 * Sets the competencia of this ponto dia.
	 *
	 * @param Competencia the competencia of this ponto dia
	 */
	public void setCompetencia(String Competencia);

	/**
	 * Returns the horas_ trabalhadas of this ponto dia.
	 *
	 * @return the horas_ trabalhadas of this ponto dia
	 */
	public int getHoras_Trabalhadas();

	/**
	 * Sets the horas_ trabalhadas of this ponto dia.
	 *
	 * @param Horas_Trabalhadas the horas_ trabalhadas of this ponto dia
	 */
	public void setHoras_Trabalhadas(int Horas_Trabalhadas);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PontoDia pontoDia);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PontoDia> toCacheModel();

	@Override
	public PontoDia toEscapedModel();

	@Override
	public PontoDia toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}