/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.desafio.ponto.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.desafio.ponto.model.PontoMarcacoes;
import com.desafio.ponto.service.PontoMarcacoesLocalServiceUtil;

/**
 * The extended model base implementation for the PontoMarcacoes service. Represents a row in the &quot;ponto_marcacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PontoMarcacoesImpl}.
 * </p>
 *
 * @author Peterson Morais
 * @see PontoMarcacoesImpl
 * @see PontoMarcacoes
 * @generated
 */
@ProviderType
public abstract class PontoMarcacoesBaseImpl extends PontoMarcacoesModelImpl
	implements PontoMarcacoes {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ponto marcacoes model instance should use the {@link PontoMarcacoes} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PontoMarcacoesLocalServiceUtil.addPontoMarcacoes(this);
		}
		else {
			PontoMarcacoesLocalServiceUtil.updatePontoMarcacoes(this);
		}
	}
}