/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.desafio.ponto.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.desafio.ponto.model.PontoMarcacoes;
import com.desafio.ponto.model.PontoMarcacoesModel;
import com.desafio.ponto.model.PontoMarcacoesSoap;
import com.desafio.ponto.service.persistence.PontoMarcacoesPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PontoMarcacoes service. Represents a row in the &quot;ponto_marcacao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PontoMarcacoesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PontoMarcacoesImpl}.
 * </p>
 *
 * @author Peterson Morais
 * @see PontoMarcacoesImpl
 * @see PontoMarcacoes
 * @see PontoMarcacoesModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PontoMarcacoesModelImpl extends BaseModelImpl<PontoMarcacoes>
	implements PontoMarcacoesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ponto marcacoes model instance should use the {@link PontoMarcacoes} interface instead.
	 */
	public static final String TABLE_NAME = "ponto_marcacao";
	public static final Object[][] TABLE_COLUMNS = {
			{ "Pis", Types.BIGINT },
			{ "DataHora", Types.BIGINT },
			{ "Marcacao_valida", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Pis", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DataHora", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Marcacao_valida", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table ponto_marcacao (Pis LONG not null,DataHora LONG not null,Marcacao_valida BOOLEAN,primary key (Pis, DataHora))";
	public static final String TABLE_SQL_DROP = "drop table ponto_marcacao";
	public static final String ORDER_BY_JPQL = " ORDER BY pontoMarcacoes.id.Pis ASC, pontoMarcacoes.id.DataHora ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ponto_marcacao.Pis ASC, ponto_marcacao.DataHora ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.desafio.ponto.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.desafio.ponto.model.PontoMarcacoes"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.desafio.ponto.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.desafio.ponto.model.PontoMarcacoes"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PontoMarcacoes toModel(PontoMarcacoesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PontoMarcacoes model = new PontoMarcacoesImpl();

		model.setPis(soapModel.getPis());
		model.setDataHora(soapModel.getDataHora());
		model.setMarcacao_valida(soapModel.isMarcacao_valida());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PontoMarcacoes> toModels(PontoMarcacoesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PontoMarcacoes> models = new ArrayList<PontoMarcacoes>(soapModels.length);

		for (PontoMarcacoesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.desafio.ponto.service.util.ServiceProps.get(
				"lock.expiration.time.com.desafio.ponto.model.PontoMarcacoes"));

	public PontoMarcacoesModelImpl() {
	}

	@Override
	public PontoMarcacoesPK getPrimaryKey() {
		return new PontoMarcacoesPK(_Pis, _DataHora);
	}

	@Override
	public void setPrimaryKey(PontoMarcacoesPK primaryKey) {
		setPis(primaryKey.Pis);
		setDataHora(primaryKey.DataHora);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new PontoMarcacoesPK(_Pis, _DataHora);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((PontoMarcacoesPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PontoMarcacoes.class;
	}

	@Override
	public String getModelClassName() {
		return PontoMarcacoes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("Pis", getPis());
		attributes.put("DataHora", getDataHora());
		attributes.put("Marcacao_valida", isMarcacao_valida());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long Pis = (Long)attributes.get("Pis");

		if (Pis != null) {
			setPis(Pis);
		}

		Long DataHora = (Long)attributes.get("DataHora");

		if (DataHora != null) {
			setDataHora(DataHora);
		}

		Boolean Marcacao_valida = (Boolean)attributes.get("Marcacao_valida");

		if (Marcacao_valida != null) {
			setMarcacao_valida(Marcacao_valida);
		}
	}

	@JSON
	@Override
	public long getPis() {
		return _Pis;
	}

	@Override
	public void setPis(long Pis) {
		_Pis = Pis;
	}

	@JSON
	@Override
	public long getDataHora() {
		return _DataHora;
	}

	@Override
	public void setDataHora(long DataHora) {
		_DataHora = DataHora;
	}

	@JSON
	@Override
	public boolean getMarcacao_valida() {
		return _Marcacao_valida;
	}

	@JSON
	@Override
	public boolean isMarcacao_valida() {
		return _Marcacao_valida;
	}

	@Override
	public void setMarcacao_valida(boolean Marcacao_valida) {
		_Marcacao_valida = Marcacao_valida;
	}

	@Override
	public PontoMarcacoes toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PontoMarcacoes)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PontoMarcacoesImpl pontoMarcacoesImpl = new PontoMarcacoesImpl();

		pontoMarcacoesImpl.setPis(getPis());
		pontoMarcacoesImpl.setDataHora(getDataHora());
		pontoMarcacoesImpl.setMarcacao_valida(isMarcacao_valida());

		pontoMarcacoesImpl.resetOriginalValues();

		return pontoMarcacoesImpl;
	}

	@Override
	public int compareTo(PontoMarcacoes pontoMarcacoes) {
		PontoMarcacoesPK primaryKey = pontoMarcacoes.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PontoMarcacoes)) {
			return false;
		}

		PontoMarcacoes pontoMarcacoes = (PontoMarcacoes)obj;

		PontoMarcacoesPK primaryKey = pontoMarcacoes.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PontoMarcacoes> toCacheModel() {
		PontoMarcacoesCacheModel pontoMarcacoesCacheModel = new PontoMarcacoesCacheModel();

		pontoMarcacoesCacheModel.pontoMarcacoesPK = getPrimaryKey();

		pontoMarcacoesCacheModel.Pis = getPis();

		pontoMarcacoesCacheModel.DataHora = getDataHora();

		pontoMarcacoesCacheModel.Marcacao_valida = isMarcacao_valida();

		return pontoMarcacoesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{Pis=");
		sb.append(getPis());
		sb.append(", DataHora=");
		sb.append(getDataHora());
		sb.append(", Marcacao_valida=");
		sb.append(isMarcacao_valida());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.desafio.ponto.model.PontoMarcacoes");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>Pis</column-name><column-value><![CDATA[");
		sb.append(getPis());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DataHora</column-name><column-value><![CDATA[");
		sb.append(getDataHora());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Marcacao_valida</column-name><column-value><![CDATA[");
		sb.append(isMarcacao_valida());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = PontoMarcacoes.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			PontoMarcacoes.class, ModelWrapper.class
		};
	private long _Pis;
	private long _DataHora;
	private boolean _Marcacao_valida;
	private PontoMarcacoes _escapedModel;
}